repos:  
  - repo: https://github.com/pylint-dev/pylint
    rev: "v3.3.7"
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args:
          [
            "--ignore=no_check*,__init__.py",
            "--max-line-length=90",
            "--const-naming-style=any",
            "--disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305,line-too-long,C0303,E2515"
          ]
        additional_dependencies: [pylint]
  
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-pylint
        name: nbqa-pylint
        description: Run 'pylint' on a Jupyter Notebook
        entry: nbqa pylint
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [pylint]
        args:
          - --ignore=no_check*,__init__.py
          - --max-line-length=90
          - --const-naming-style=any
          - --disable=E0401,W0104,R0903,R1721,E1101,E0611,F0002,C0305,C0303,E2515

  - repo: https://github.com/psf/black.git
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        name: nbqa-black
        description: Run 'black' on a Jupyter Notebook
        entry: nbqa black
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies: [black]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.16.1"
    hooks:
      - id: mypy
        args:
          # - --cache-dir=/dev/null
          # - --cache-dir=nul
          # - --no-incremental
          - --non-interactive
          - --install-types
          - --explicit-package-bases
          - --ignore-missing-imports
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-untyped-decorators
          - --strict
          - --extra-checks
          - --disallow-any-decorated
          - --disallow-any-generics
          - --local-partial-types
          - --pretty
          - --force-uppercase-builtins
          - --force-union-syntax
          - --warn-unreachable
          - --warn-redundant-casts
          - --warn-return-any
          - --disallow-any-explicit
        additional_dependencies:
          - mypy
          - pandas-stubs
          - git+https://github.com/numpy/numpy-stubs
          - mypy-extensions
          - types-requests
          - types-PyYAML
          - types-setuptools

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-mypy
        name: nbqa-mypy
        description: Run 'mypy' on a Jupyter Notebook
        entry: nbqa mypy
        language: python
        require_serial: true
        types_or: [jupyter, markdown]
        additional_dependencies:
          - mypy
          - pandas-stubs
          - git+https://github.com/numpy/numpy-stubs
          - mypy-extensions
          - types-requests
          - types-PyYAML
          - types-setuptools
        args:
          # - --cache-dir=/dev/null
          # - --cache-dir=nul
          # - --no-incremental
          - --non-interactive
          - --install-types
          - --explicit-package-bases
          - --ignore-missing-imports
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-untyped-decorators
          - --strict
          - --extra-checks
          - --disallow-any-decorated
          - --disallow-any-generics
          - --local-partial-types
          - --pretty
          - --force-uppercase-builtins
          - --force-union-syntax
          - --warn-unreachable
          - --warn-redundant-casts
          - --warn-return-any
          - --disallow-any-explicit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-yaml
    - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format